---
- hosts: localhost
  connection: local
  name: Configure local machine
  vars:
    downloads: "{{ansible_env.HOME}}/.ansible-downloads"
    applications_dir: "/Applications"
    mount_path: /Volumes
    data_dir: "{{ lookup('env', 'HOME') }}/data"
  pre_tasks:
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: "{{ data_dir }}"
      state: directory
      mode: '0755'
  # - name: Login to app store warning.
  #   pause:
  #     prompt: "Make sure you login to the apple app store before continuing."
  tasks:
  - name: Read machine hostname var
    ansible.builtin.shell: hostname
    register: machine_hostname
  - set_fact: machine_hostname={{ machine_hostname.stdout }}
  - name: Create Ansible downloads directory
    file: path={{ downloads }} state=directory
  - name: Setting installer source to "{{ downloads }}"
    set_fact:
      installer_source: "{{downloads}}"
  - include: tasks/core/main.yml
  - include: tasks/homebrew/main.yml
    when: ansible_facts['os_family'] == "Darwin"
  - include: tasks/adobe/main.yml
    when: ansible_facts['os_family'] == "Darwin"
    with_items:
    # - { name: "Adobe Creative Cloud", id: "LRCC", downloadName: "Lightroom", installerName: "Lightroom Installer", finalAppName: 'Adobe Creative Cloud' }
    - { name: "Lightroom", id: "LRCC", downloadName: "Lightroom", installerName: "Lightroom Installer", finalAppName: 'Adobe Lightroom CC' }
    - { name: "Acrobat DC", id: "APRO", downloadName: "Adobe Acrobat DC", installerName: "Acrobat DC Installer", finalAppName: 'Adobe Acrobat DC' }
    - { name: "Photoshop", id: "PHSP", downloadName: "Photoshop", installerName: "Photoshop Installer", finalAppName: 'Adobe Photoshop 2022' }
    loop_control:
      loop_var: item
  - include: tasks/mac/main.yml
    when: ansible_facts['os_family'] == "Darwin"


