---
- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: "{{ machine_hostname }} access key"
    token: '{{ github_access_token }}'
    pubkey: "{{ lookup('file', \"{{ ansible_env.HOME }}/.ssh/id_ed25519.pub\") }}"
  tags:
  - ssh
  - github
- name: Validate GitHub Access
  ansible.builtin.shell: |
    ssh -T -o StrictHostKeyChecking=accept-new git@github.com
  register: test_github_ssh
  failed_when:
  - test_github_ssh.rc != 1
  - ("You've successfully authenticated, but GitHub does not provide shell access." not in result.stdout)
  tags:
  - ssh
  - github
