---
- name: Generate SSH Key
  ansible.builtin.shell:
    cmd: ssh-keygen -t ed25519 -C "{{ my_email }}" -f "{{ ansible_env.HOME }}/.ssh/id_ed25519" -q -P "{{ my_ssh_passphrase }}" && eval "$(ssh-agent -s)"
    creates: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  tags:
  - install
  - ssh
- name: Copy SSH Config
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', './files/.ssh/config') }}"
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: present
    create: true
    backup: true
  tags:
  - install
  - ssh
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', \"{{ ansible_env.HOME }}/.ssh/id_ed25519.pub\") }}"
  tags:
  - install
  - ssh
