---
# Sign in manually, prompted in beginning
# - name: Sign in to Apple Store
#   ansible.builtin.script:
#     cmd: osascript ./files/signin_to_appstore.applescript "{{ apple_store_email }}" "{{ apple_store_password }}"
- name: Install From App Store
  community.general.mas:
    id:
      - 1423210932 # Flow
      - 408981434 # imovie
      - 409203825 # numbers
      - 409201541 # pages
    state: present
    upgrade_all: yes
  tags:
  - apple
  - install
  - essential
- name: Install From App Store
  community.general.mas:
    id:
      - 411643860 # Daisy Disk
      - 441258766 # Magnet
      - 1303222628 # Paprika
      - 497799835 # xcode # temp, out of disk space
      - 904280696 # things 3
      - 431748264 # pluralsight
    state: present
    upgrade_all: yes
  tags:
  - apple
  - install
- name: Configure terminal themes
  ansible.builtin.shell: |
    cp -f "{{ ansible_facts['env']['PWD'] }}/terminal/{{ item }}" "{{ ansible_facts['env']['PWD'] }}/terminal/modified_themes/"
    terminal_defaults="${HOME}/Library/Preferences/com.apple.Terminal.plist"
    theme="{{ ansible_facts['env']['PWD'] }}/terminal/modified_themes/{{ item }}"
    name=$(plutil -extract "name" xml1 -o - ${theme} | plutil -p -)
    font_data='YnBsaXN0MDDUAQIDBAUGGBlYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKQHCBESVSRudWxs1AkKCwwNDg8QVk5TU2l6ZVhOU2ZGbGFnc1ZOU05hbWVWJGNsYXNzI0AqAAAAAAAAEBCAAoADXxAcSGFja05lcmRGb250Q29tcGxldGUtUmVndWxhctITFBUWWiRjbGFzc25hbWVYJGNsYXNzZXNWTlNGb250ohUXWE5TT2JqZWN0XxAPTlNLZXllZEFyY2hpdmVy0RobVHJvb3SAAQgRGiMtMjc8QktSW2JpcnR2eJecp7C3usPV2N0AAAAAAAABAQAAAAAAAAAcAAAAAAAAAAAAAAAAAAAA3w=='
    plutil -replace "Font" -data "${font_data}" "${theme}"
    plutil -replace "Window Settings"."${name//\"}" -xml """$(cat "${theme}")""" "${terminal_defaults}"
    exit 0
  loop:
  - materialshell-dark.terminal
  - materialshell-oceanic.terminal
  register: terminal_themes
  failed_when: terminal_themes.rc != 0
  tags:
  - essential
  - zsh
  - configure
- name: Configure default terminal themes
  ansible.builtin.shell: |
    defaults write com.apple.Terminal "Startup Window Settings" "Material Shell - Dark"
    defaults write com.apple.Terminal "Default Window Settings" "Material Shell - Dark"
    exit 0
  register: default_terminal_themes
  failed_when: default_terminal_themes.rc != 0
  tags:
  - essential
  - zsh
  - configure
